# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-Emoticon
version:      0.02
version_from: lib/Text/Emoticon.pm
installdirs:  site
requires:
    Test::More:                    0.32
    UNIVERSAL::require:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
